### ISSUE TITLE
Replit issues 

### ISSUE THREAD

**Issue by Osama-Al-Ahmad** [PgerTools/MSMC-Inboxer#6]
How can I run the script in replit , I tried to run it in Rplit but I have a problem (Sorry for my english)
![Screenshot_٢٠٢٤٠٧١٨-٢١٥٧٠٧](https://github.com/user-attachments/assets/a640232a-739b-4ebc-8544-1630b6995240)

**Comment by PgerTools** [comment]
I am not sure. I haven't used replit in a very long time and it has changed a lot. I would recommend googling how to use replit for python. MSMC with Inboxer should be able to run on replit.

**Comment by PgerTools** [comment]
If you have access to a computer I would recommend running it on that because it will be way faster with less issues.
